name: release-client

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: ver
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --list "v0.0.*" --sort=-v:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then
            NEW_VERSION="v0.0.1"
          else
            LAST_NUM=$(echo $LAST_TAG | cut -d '.' -f 3)
            NEW_VERSION="v0.0.$((LAST_NUM + 1))"
          fi

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: version
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build client
        run: |
          mkdir -p dist

          OUT="dist/wormhole-client-${{ matrix.goos }}-${{ matrix.goarch }}"

          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUT="${OUT}.exe"
          fi

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o $OUT ./cmd/client

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    needs: [version, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          find dist -type f -exec mv {} dist/ \;
          find dist -type d -empty -delete

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.version }}
          name: ${{ needs.version.outputs.version }}
          files: dist/*ƒ